In [0]:
import torch

In [4]:
x = torch.rand(441000, 1)
y = torch.rand(441000, 1)

print(x)
print(y)

tensor([[0.1901],
        [0.8517],
        [0.6016],
        ...,
        [0.3039],
        [0.8715],
        [0.4792]])
tensor([[0.8496],
        [0.9476],
        [0.3685],
        ...,
        [0.1342],
        [0.9043],
        [0.4309]])


In [9]:
z = torch.cat((x, y), 1)
print(z)
print(z.shape)

tensor([[0.1901, 0.8496],
        [0.8517, 0.9476],
        [0.6016, 0.3685],
        ...,
        [0.3039, 0.1342],
        [0.8715, 0.9043],
        [0.4792, 0.4309]])
torch.Size([441000, 2])


In [13]:
z1 = torch.stack((x, y))
print(z1)
print(z1.shape)

tensor([[[0.1901],
         [0.8517],
         [0.6016],
         ...,
         [0.3039],
         [0.8715],
         [0.4792]],

        [[0.8496],
         [0.9476],
         [0.3685],
         ...,
         [0.1342],
         [0.9043],
         [0.4309]]])
torch.Size([2, 441000, 1])


In [26]:
a = torch.rand(441000)
b = torch.rand(441000)

print(a.shape, b.shape)

torch.Size([441000]) torch.Size([441000])


In [27]:
c = torch.cat((a,b), 0)
print(c, c.shape)

tensor([0.8814, 0.9932, 0.6960,  ..., 0.0498, 0.6526, 0.9860]) torch.Size([882000])


In [28]:
a = a.reshape(441000, 1)
b = b.reshape(441000, 1)

print(a.shape, b.shape)

torch.Size([441000, 1]) torch.Size([441000, 1])


In [29]:
c = torch.cat((a,b), 1)
print(c, c.shape)

tensor([[0.8814, 0.5463],
        [0.9932, 0.2379],
        [0.6960, 0.0782],
        ...,
        [0.5893, 0.0498],
        [0.7542, 0.6526],
        [0.9907, 0.9860]]) torch.Size([441000, 2])


In [30]:
i = torch.rand(1, 441000, 1)
j = torch.rand(1, 441000, 1)

print(i.shape, j.shape)

torch.Size([1, 441000, 1]) torch.Size([1, 441000, 1])


In [31]:
k = torch.cat((i,j), 2)
print(k.shape)

torch.Size([1, 441000, 2])
